global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: custom_exporter
    static_configs:
      - targets: ["custom-exporter:8000"]

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: postgres_exporter
    honor_labels: true
    static_configs:
      - targets: ["pg-exporter:9187"]

  - job_name: node-windows
    static_configs:
      - targets: ["host.docker.internal:9182"]
    
